### ISSUE TITLE
Signify 0.6.0 only compatible with Python 3.11+

### ISSUE THREAD

**Issue by dinateper** [ralphje/signify#43]
On the PyPI page, it states signify is compatible with Python 3.8+.
However, in [signify/pkcs7/signeddata.py](https://github.com/ralphje/signify/blob/b6ce0c365174db115ce60782ae3d3e3ae4ca590f/signify/pkcs7/signeddata.py) and [signify/authenticode/authroot.py](https://github.com/ralphje/signify/blob/b6ce0c365174db115ce60782ae3d3e3ae4ca590f/signify/authenticode/authroot.py) `Self` is used.
The `Self` PEP is only officially supported starting python 3.11, making signify incompatible with older python versions.

**Comment by ralphje** [comment]
This should not be an issue since we use `typing_extensions` for that. Are you running into any concrete issues?

**Comment by ralphje** [comment]
Perhaps `typing_extensions` should have been pinned to at least version 4.6.0 (`Self` should be present since 4.0.1). I've added this to `setup.py`.

If you are running into any issues, you could try and `pip install -U typing_extensions` yourself. If that fixes anything, please let me know so we can release this fix soon. Otherwise, we could debug a bit further.

**Comment by dinateper** [comment]
Upgrading `typing_extensions` did the trick :)
Thank you!

**Comment by ralphje** [comment]
Released as version 0.6.1
