### ISSUE TITLE
Going crazy due to incorrect sign dates

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ralphje/signify#45]
Hello, and thank you for this library.

In recent days, I found some inconsistency in my data, and I went crazy trying to understand what causes it. It's a bizarre inconsistency with dates such as the following, while they're supposed to be identical:
`2016-08-06 11:59:52.018000+00:00`
`2016-08-06 11:59:52.180000+00:00`

After checking lots of stuff such as my code, the serialization lib and the compression lib, I finally found that it was about an old version of signify. Here's a reproduction:

https://github.com/justanotheranonymoususer/signify-dates-bug/actions/runs/11271230691/job/31343636892

As you can see, 0.6.x and 0.7.x return different values.

It looks like the newer version is correct, so the issue is not a bug report, I just want to make sure that the bug is known and make sure it's not going to return.

Also, it might be one of the dependencies. Refer me to the relevant dependency if that's the case.

**Comment by ralphje** [comment]
Sorry that this has taken so long to investigate, but the issue is clearly somewhere in pyasn1 code. We use the conversion in the `asDateTime` method as provided by pyasn1, as shown [here](https://github.com/ralphje/signify/blob/v0.6.1/signify/authenticode/structures.py#L666).

In the case of your example, the relevant GeneralizedTime object of the TSTInfo object is as follows:
```
>>> list(pe.signed_datas)[0].signer_info.countersigner.tst_info.data["genTime"]
<GeneralizedTime value object, tagSet <TagSet object, tags 0:0:24>, encoding us-ascii, payload [20160806115952.18Z]>
```

From the method defined [here in pyasn1](https://github.com/pyasn1/pyasn1/blob/main/pyasn1/type/useful.py#L60-L124), it seems that the code assumes a certain number of decimals after the decimal separator (as it multiplies by 1000). In the case of your provided sample, it is clear that there are only 2 decimals provided.

Switching to asn1crypto seems to have resolved this issue as well. The [relevant part](https://github.com/wbond/asn1crypto/blob/master/asn1crypto/core.py#L4932-L4947) of that class takes a variable number of decimals into account.

I have added a test that should mark this as an issue in the future. The test fails on 0.6.1 and succeeds on master.

**Comment by justanotheranonymoususer** [comment]
Thank you for confirming and adding a test. I opened an upstream issue here: https://github.com/ralphje/signify/issues/48.
